// LGPL-2.1-or-later

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void go_nix_store_realise_callback_8324f29f(void* userdata, char* outname, StorePath* out) {
	storeRealiseCallback8324F29F(userdata, outname, out);
}

void go_nix_store_path_callback_d85f7e1(nix_c_context* context, void* userdata, StorePath* store_path) {
	storePathCallbackD85F7E1(context, userdata, store_path);
}

