// LGPL-2.1-or-later

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "nix_go_util.h"
#include "nix_go_store.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// go_nix_store_realise_callback_8324f29f is a proxy for callback go_nix_store_realise_callback.
void go_nix_store_realise_callback_8324f29f(void* userdata, char* outname, StorePath* out);

// go_nix_store_path_callback_d85f7e1 is a proxy for callback go_nix_store_path_callback.
void go_nix_store_path_callback_d85f7e1(nix_c_context* context, void* userdata, StorePath* store_path);

