// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c nix-fetchers-c
#include "nix_go_util.h"
#include "nix_go_store.h"
#include "nix_go_fetchers.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *Store) Ref() *C.Store {
	if x == nil {
		return nil
	}
	return (*C.Store)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Store) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewStoreRef converts the C object reference into a raw struct reference without wrapping.
func NewStoreRef(ref unsafe.Pointer) *Store {
	return (*Store)(ref)
}

// NewStore allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewStore() *Store {
	return (*Store)(allocStoreMemory(1))
}

// allocStoreMemory allocates memory for type C.Store in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreValue = unsafe.Sizeof([1]C.Store{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Store) PassRef() *C.Store {
	if x == nil {
		x = (*Store)(allocStoreMemory(1))
	}
	return (*C.Store)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixDerivation) Ref() *C.nix_derivation {
	if x == nil {
		return nil
	}
	return (*C.nix_derivation)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixDerivation) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixDerivationRef converts the C object reference into a raw struct reference without wrapping.
func NewNixDerivationRef(ref unsafe.Pointer) *NixDerivation {
	return (*NixDerivation)(ref)
}

// NewNixDerivation allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixDerivation() *NixDerivation {
	return (*NixDerivation)(allocNixDerivationMemory(1))
}

// allocNixDerivationMemory allocates memory for type C.nix_derivation in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixDerivationMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixDerivationValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixDerivationValue = unsafe.Sizeof([1]C.nix_derivation{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixDerivation) PassRef() *C.nix_derivation {
	if x == nil {
		x = (*NixDerivation)(allocNixDerivationMemory(1))
	}
	return (*C.nix_derivation)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *StorePath) Ref() *C.StorePath {
	if x == nil {
		return nil
	}
	return (*C.StorePath)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *StorePath) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewStorePathRef converts the C object reference into a raw struct reference without wrapping.
func NewStorePathRef(ref unsafe.Pointer) *StorePath {
	return (*StorePath)(ref)
}

// NewStorePath allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewStorePath() *StorePath {
	return (*StorePath)(allocStorePathMemory(1))
}

// allocStorePathMemory allocates memory for type C.StorePath in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStorePathMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStorePathValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStorePathValue = unsafe.Sizeof([1]C.StorePath{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *StorePath) PassRef() *C.StorePath {
	if x == nil {
		x = (*StorePath)(allocStorePathMemory(1))
	}
	return (*C.StorePath)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixFetchersSettings) Ref() *C.nix_fetchers_settings {
	if x == nil {
		return nil
	}
	return (*C.nix_fetchers_settings)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixFetchersSettings) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixFetchersSettingsRef converts the C object reference into a raw struct reference without wrapping.
func NewNixFetchersSettingsRef(ref unsafe.Pointer) *NixFetchersSettings {
	return (*NixFetchersSettings)(ref)
}

// NewNixFetchersSettings allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixFetchersSettings() *NixFetchersSettings {
	return (*NixFetchersSettings)(allocNixFetchersSettingsMemory(1))
}

// allocNixFetchersSettingsMemory allocates memory for type C.nix_fetchers_settings in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixFetchersSettingsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixFetchersSettingsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixFetchersSettingsValue = unsafe.Sizeof([1]C.nix_fetchers_settings{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixFetchersSettings) PassRef() *C.nix_fetchers_settings {
	if x == nil {
		x = (*NixFetchersSettings)(allocNixFetchersSettingsMemory(1))
	}
	return (*C.nix_fetchers_settings)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixCContext) Ref() *C.nix_c_context {
	if x == nil {
		return nil
	}
	return (*C.nix_c_context)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixCContext) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixCContextRef converts the C object reference into a raw struct reference without wrapping.
func NewNixCContextRef(ref unsafe.Pointer) *NixCContext {
	return (*NixCContext)(ref)
}

// NewNixCContext allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixCContext() *NixCContext {
	return (*NixCContext)(allocNixCContextMemory(1))
}

// allocNixCContextMemory allocates memory for type C.nix_c_context in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixCContextMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixCContextValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixCContextValue = unsafe.Sizeof([1]C.nix_c_context{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixCContext) PassRef() *C.nix_c_context {
	if x == nil {
		x = (*NixCContext)(allocNixCContextMemory(1))
	}
	return (*C.nix_c_context)(unsafe.Pointer(x))
}

// allocStoreParamMemory allocates memory for type C.go_nix_store_param in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreParamMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreParamValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreParamValue = unsafe.Sizeof([1]C.go_nix_store_param{})

// copyPCharBytes copies the data from Go slice as *C.char.
func copyPCharBytes(slice *sliceHeader) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfCharValue) * slice.Len,
		Cap:  int(sizeOfCharValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.char)(mem0), allocs
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocCharMemory allocates memory for type C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfCharValue = unsafe.Sizeof([1]C.char{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StoreParam) Ref() *C.go_nix_store_param {
	if x == nil {
		return nil
	}
	return x.ref2b71aeb
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StoreParam) Free() {
	if x != nil && x.allocs2b71aeb != nil {
		x.allocs2b71aeb.(*cgoAllocMap).Free()
		x.ref2b71aeb = nil
	}
}

// NewStoreParamRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStoreParamRef(ref unsafe.Pointer) *StoreParam {
	if ref == nil {
		return nil
	}
	obj := new(StoreParam)
	obj.ref2b71aeb = (*C.go_nix_store_param)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StoreParam) PassRef() (*C.go_nix_store_param, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref2b71aeb != nil {
		return x.ref2b71aeb, nil
	}
	mem2b71aeb := allocStoreParamMemory(1)
	ref2b71aeb := (*C.go_nix_store_param)(mem2b71aeb)
	allocs2b71aeb := new(cgoAllocMap)
	allocs2b71aeb.Add(mem2b71aeb)

	var ckey_allocs *cgoAllocMap
	ref2b71aeb.key, ckey_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Key)))
	allocs2b71aeb.Borrow(ckey_allocs)

	var cvalue_allocs *cgoAllocMap
	ref2b71aeb.value, cvalue_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Value)))
	allocs2b71aeb.Borrow(cvalue_allocs)

	x.ref2b71aeb = ref2b71aeb
	x.allocs2b71aeb = allocs2b71aeb
	return ref2b71aeb, allocs2b71aeb

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StoreParam) PassValue() (C.go_nix_store_param, *cgoAllocMap) {
	if x.ref2b71aeb != nil {
		return *x.ref2b71aeb, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StoreParam) Deref() {
	if x.ref2b71aeb == nil {
		return
	}
	hxfc4425b := (*sliceHeader)(unsafe.Pointer(&x.Key))
	hxfc4425b.Data = unsafe.Pointer(x.ref2b71aeb.key)
	hxfc4425b.Cap = 0x7fffffff
	// hxfc4425b.Len = ? x.Key x.ref2b71aeb.key

	hxf95e7c8 := (*sliceHeader)(unsafe.Pointer(&x.Value))
	hxf95e7c8.Data = unsafe.Pointer(x.ref2b71aeb.value)
	hxf95e7c8.Cap = 0x7fffffff
	// hxf95e7c8.Len = ? x.Value x.ref2b71aeb.value

}

// allocStoreParamsMemory allocates memory for type C.go_nix_store_params in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreParamsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreParamsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreParamsValue = unsafe.Sizeof([1]C.go_nix_store_params{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackSStoreParam transforms a sliced Go data structure into plain C format.
func unpackSStoreParam(x []StoreParam) (unpacked *C.go_nix_store_param, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStoreParamMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.go_nix_store_param)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.go_nix_store_param)(h.Data)
	return
}

// packSStoreParam reads sliced Go data structure out from plain C format.
func packSStoreParam(v []StoreParam, ptr0 *C.go_nix_store_param) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStoreParamValue]C.go_nix_store_param)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewStoreParamRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StoreParams) Ref() *C.go_nix_store_params {
	if x == nil {
		return nil
	}
	return x.ref2cd443e1
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StoreParams) Free() {
	if x != nil && x.allocs2cd443e1 != nil {
		x.allocs2cd443e1.(*cgoAllocMap).Free()
		x.ref2cd443e1 = nil
	}
}

// NewStoreParamsRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStoreParamsRef(ref unsafe.Pointer) *StoreParams {
	if ref == nil {
		return nil
	}
	obj := new(StoreParams)
	obj.ref2cd443e1 = (*C.go_nix_store_params)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StoreParams) PassRef() (*C.go_nix_store_params, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref2cd443e1 != nil {
		return x.ref2cd443e1, nil
	}
	mem2cd443e1 := allocStoreParamsMemory(1)
	ref2cd443e1 := (*C.go_nix_store_params)(mem2cd443e1)
	allocs2cd443e1 := new(cgoAllocMap)
	allocs2cd443e1.Add(mem2cd443e1)

	var citems_allocs *cgoAllocMap
	ref2cd443e1.items, citems_allocs = unpackSStoreParam(x.Items)
	allocs2cd443e1.Borrow(citems_allocs)

	var clen_allocs *cgoAllocMap
	ref2cd443e1.len, clen_allocs = (C.size_t)(x.Len), cgoAllocsUnknown
	allocs2cd443e1.Borrow(clen_allocs)

	x.ref2cd443e1 = ref2cd443e1
	x.allocs2cd443e1 = allocs2cd443e1
	return ref2cd443e1, allocs2cd443e1

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StoreParams) PassValue() (C.go_nix_store_params, *cgoAllocMap) {
	if x.ref2cd443e1 != nil {
		return *x.ref2cd443e1, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StoreParams) Deref() {
	if x.ref2cd443e1 == nil {
		return
	}
	packSStoreParam(x.Items, x.ref2cd443e1.items)
	x.Len = (uint64)(x.ref2cd443e1.len)
}

// allocStorePathHashPartMemory allocates memory for type C.go_nix_store_path_hash_part in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStorePathHashPartMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStorePathHashPartValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStorePathHashPartValue = unsafe.Sizeof([1]C.go_nix_store_path_hash_part{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StorePathHashPart) Ref() *C.go_nix_store_path_hash_part {
	if x == nil {
		return nil
	}
	return x.reff3a80ce6
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StorePathHashPart) Free() {
	if x != nil && x.allocsf3a80ce6 != nil {
		x.allocsf3a80ce6.(*cgoAllocMap).Free()
		x.reff3a80ce6 = nil
	}
}

// NewStorePathHashPartRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStorePathHashPartRef(ref unsafe.Pointer) *StorePathHashPart {
	if ref == nil {
		return nil
	}
	obj := new(StorePathHashPart)
	obj.reff3a80ce6 = (*C.go_nix_store_path_hash_part)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StorePathHashPart) PassRef() (*C.go_nix_store_path_hash_part, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.reff3a80ce6 != nil {
		return x.reff3a80ce6, nil
	}
	memf3a80ce6 := allocStorePathHashPartMemory(1)
	reff3a80ce6 := (*C.go_nix_store_path_hash_part)(memf3a80ce6)
	allocsf3a80ce6 := new(cgoAllocMap)
	allocsf3a80ce6.Add(memf3a80ce6)

	var cbytes_allocs *cgoAllocMap
	reff3a80ce6.bytes, cbytes_allocs = *(*[20]C.uchar)(unsafe.Pointer(&x.Bytes)), cgoAllocsUnknown
	allocsf3a80ce6.Borrow(cbytes_allocs)

	x.reff3a80ce6 = reff3a80ce6
	x.allocsf3a80ce6 = allocsf3a80ce6
	return reff3a80ce6, allocsf3a80ce6

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StorePathHashPart) PassValue() (C.go_nix_store_path_hash_part, *cgoAllocMap) {
	if x.reff3a80ce6 != nil {
		return *x.reff3a80ce6, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StorePathHashPart) Deref() {
	if x.reff3a80ce6 == nil {
		return
	}
	x.Bytes = *(*[20]byte)(unsafe.Pointer(&x.reff3a80ce6.bytes))
}

// packPCharString creates a Go string backed by *C.char and avoids copying.
func packPCharString(p *C.char) (raw string) {
	if p != nil && *p != 0 {
		h := (*stringHeader)(unsafe.Pointer(&raw))
		h.Data = unsafe.Pointer(p)
		for *p != 0 {
			p = (*C.char)(unsafe.Pointer(uintptr(unsafe.Pointer(p)) + 1)) // p++
		}
		h.Len = int(uintptr(unsafe.Pointer(p)) - uintptr(h.Data))
	}
	return
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

// RawString reperesents a string backed by data on the C side.
type RawString string

// Copy returns a Go-managed copy of raw string.
func (raw RawString) Copy() string {
	if len(raw) == 0 {
		return ""
	}
	h := (*stringHeader)(unsafe.Pointer(&raw))
	return C.GoStringN((*C.char)(h.Data), C.int(h.Len))
}

func (x StoreRealiseCallback) PassRef() (ref *C.go_nix_store_realise_callback, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if storeRealiseCallback8324F29FFunc == nil {
		storeRealiseCallback8324F29FFunc = x
	}
	return (*C.go_nix_store_realise_callback)(C.go_nix_store_realise_callback_8324f29f), nil
}

func (x StoreRealiseCallback) PassValue() (ref C.go_nix_store_realise_callback, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if storeRealiseCallback8324F29FFunc == nil {
		storeRealiseCallback8324F29FFunc = x
	}
	return (C.go_nix_store_realise_callback)(C.go_nix_store_realise_callback_8324f29f), nil
}

func NewStoreRealiseCallbackRef(ref unsafe.Pointer) *StoreRealiseCallback {
	return (*StoreRealiseCallback)(ref)
}

//export storeRealiseCallback8324F29F
func storeRealiseCallback8324F29F(cuserdata unsafe.Pointer, coutname *C.char, cout *C.StorePath) {
	if storeRealiseCallback8324F29FFunc != nil {
		userdata8324f29f := (unsafe.Pointer)(unsafe.Pointer(cuserdata))
		outname8324f29f := packPCharString(coutname)
		out8324f29f := (*StorePath)(unsafe.Pointer(cout))
		storeRealiseCallback8324F29FFunc(userdata8324f29f, outname8324f29f, out8324f29f)
		return
	}
	panic("callback func has not been set (race?)")
}

var storeRealiseCallback8324F29FFunc StoreRealiseCallback

func (x StorePathCallback) PassRef() (ref *C.go_nix_store_path_callback, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if storePathCallbackD85F7E1Func == nil {
		storePathCallbackD85F7E1Func = x
	}
	return (*C.go_nix_store_path_callback)(C.go_nix_store_path_callback_d85f7e1), nil
}

func (x StorePathCallback) PassValue() (ref C.go_nix_store_path_callback, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if storePathCallbackD85F7E1Func == nil {
		storePathCallbackD85F7E1Func = x
	}
	return (C.go_nix_store_path_callback)(C.go_nix_store_path_callback_d85f7e1), nil
}

func NewStorePathCallbackRef(ref unsafe.Pointer) *StorePathCallback {
	return (*StorePathCallback)(ref)
}

//export storePathCallbackD85F7E1
func storePathCallbackD85F7E1(ccontext *C.nix_c_context, cuserdata unsafe.Pointer, cstorePath *C.StorePath) {
	if storePathCallbackD85F7E1Func != nil {
		contextd85f7e1 := (*NixCContext)(unsafe.Pointer(ccontext))
		userdatad85f7e1 := (unsafe.Pointer)(unsafe.Pointer(cuserdata))
		storePathd85f7e1 := (*StorePath)(unsafe.Pointer(cstorePath))
		storePathCallbackD85F7E1Func(contextd85f7e1, userdatad85f7e1, storePathd85f7e1)
		return
	}
	panic("callback func has not been set (race?)")
}

var storePathCallbackD85F7E1Func StorePathCallback

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}
