// LGPL-2.1-or-later

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "nix_go_util.h"
#include "nix_go_store.h"
#include "nix_go_fetchers.h"
#include "nix_go_expr.h"
#include "nix_go_flake.h"
#include "nix_go_main.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

