// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c nix-fetchers-c nix-expr-c nix-flake-c nix-main-c
#cgo CXXFLAGS: -std=c++23
#cgo LDFLAGS: -lnixflake -lnixutil
#cgo darwin LDFLAGS: -lc++
#cgo linux LDFLAGS: -lstdc++
#include "nix_go_util.h"
#include "nix_go_store.h"
#include "nix_go_fetchers.h"
#include "nix_go_expr.h"
#include "nix_go_flake.h"
#include "nix_go_main.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *NixFetchersSettings) Ref() *C.nix_fetchers_settings {
	if x == nil {
		return nil
	}
	return (*C.nix_fetchers_settings)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixFetchersSettings) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixFetchersSettingsRef converts the C object reference into a raw struct reference without wrapping.
func NewNixFetchersSettingsRef(ref unsafe.Pointer) *NixFetchersSettings {
	return (*NixFetchersSettings)(ref)
}

// NewNixFetchersSettings allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixFetchersSettings() *NixFetchersSettings {
	return (*NixFetchersSettings)(allocNixFetchersSettingsMemory(1))
}

// allocNixFetchersSettingsMemory allocates memory for type C.nix_fetchers_settings in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixFetchersSettingsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixFetchersSettingsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixFetchersSettingsValue = unsafe.Sizeof([1]C.nix_fetchers_settings{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixFetchersSettings) PassRef() *C.nix_fetchers_settings {
	if x == nil {
		x = (*NixFetchersSettings)(allocNixFetchersSettingsMemory(1))
	}
	return (*C.nix_fetchers_settings)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixEvalStateBuilder) Ref() *C.nix_eval_state_builder {
	if x == nil {
		return nil
	}
	return (*C.nix_eval_state_builder)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixEvalStateBuilder) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixEvalStateBuilderRef converts the C object reference into a raw struct reference without wrapping.
func NewNixEvalStateBuilderRef(ref unsafe.Pointer) *NixEvalStateBuilder {
	return (*NixEvalStateBuilder)(ref)
}

// NewNixEvalStateBuilder allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixEvalStateBuilder() *NixEvalStateBuilder {
	return (*NixEvalStateBuilder)(allocNixEvalStateBuilderMemory(1))
}

// allocNixEvalStateBuilderMemory allocates memory for type C.nix_eval_state_builder in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixEvalStateBuilderMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixEvalStateBuilderValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixEvalStateBuilderValue = unsafe.Sizeof([1]C.nix_eval_state_builder{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixEvalStateBuilder) PassRef() *C.nix_eval_state_builder {
	if x == nil {
		x = (*NixEvalStateBuilder)(allocNixEvalStateBuilderMemory(1))
	}
	return (*C.nix_eval_state_builder)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *EvalState) Ref() *C.EvalState {
	if x == nil {
		return nil
	}
	return (*C.EvalState)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *EvalState) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewEvalStateRef converts the C object reference into a raw struct reference without wrapping.
func NewEvalStateRef(ref unsafe.Pointer) *EvalState {
	return (*EvalState)(ref)
}

// NewEvalState allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewEvalState() *EvalState {
	return (*EvalState)(allocEvalStateMemory(1))
}

// allocEvalStateMemory allocates memory for type C.EvalState in C.
// The caller is responsible for freeing the this memory via C.free.
func allocEvalStateMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfEvalStateValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfEvalStateValue = unsafe.Sizeof([1]C.EvalState{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *EvalState) PassRef() *C.EvalState {
	if x == nil {
		x = (*EvalState)(allocEvalStateMemory(1))
	}
	return (*C.EvalState)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixValue) Ref() *C.nix_value {
	if x == nil {
		return nil
	}
	return (*C.nix_value)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixValue) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixValueRef converts the C object reference into a raw struct reference without wrapping.
func NewNixValueRef(ref unsafe.Pointer) *NixValue {
	return (*NixValue)(ref)
}

// NewNixValue allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixValue() *NixValue {
	return (*NixValue)(allocNixValueMemory(1))
}

// allocNixValueMemory allocates memory for type C.nix_value in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixValueMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixValueValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixValueValue = unsafe.Sizeof([1]C.nix_value{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixValue) PassRef() *C.nix_value {
	if x == nil {
		x = (*NixValue)(allocNixValueMemory(1))
	}
	return (*C.nix_value)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixFlakeSettings) Ref() *C.nix_flake_settings {
	if x == nil {
		return nil
	}
	return (*C.nix_flake_settings)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixFlakeSettings) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixFlakeSettingsRef converts the C object reference into a raw struct reference without wrapping.
func NewNixFlakeSettingsRef(ref unsafe.Pointer) *NixFlakeSettings {
	return (*NixFlakeSettings)(ref)
}

// NewNixFlakeSettings allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixFlakeSettings() *NixFlakeSettings {
	return (*NixFlakeSettings)(allocNixFlakeSettingsMemory(1))
}

// allocNixFlakeSettingsMemory allocates memory for type C.nix_flake_settings in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixFlakeSettingsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixFlakeSettingsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixFlakeSettingsValue = unsafe.Sizeof([1]C.nix_flake_settings{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixFlakeSettings) PassRef() *C.nix_flake_settings {
	if x == nil {
		x = (*NixFlakeSettings)(allocNixFlakeSettingsMemory(1))
	}
	return (*C.nix_flake_settings)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixFlakeReferenceParseFlags) Ref() *C.nix_flake_reference_parse_flags {
	if x == nil {
		return nil
	}
	return (*C.nix_flake_reference_parse_flags)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixFlakeReferenceParseFlags) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixFlakeReferenceParseFlagsRef converts the C object reference into a raw struct reference without wrapping.
func NewNixFlakeReferenceParseFlagsRef(ref unsafe.Pointer) *NixFlakeReferenceParseFlags {
	return (*NixFlakeReferenceParseFlags)(ref)
}

// NewNixFlakeReferenceParseFlags allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixFlakeReferenceParseFlags() *NixFlakeReferenceParseFlags {
	return (*NixFlakeReferenceParseFlags)(allocNixFlakeReferenceParseFlagsMemory(1))
}

// allocNixFlakeReferenceParseFlagsMemory allocates memory for type C.nix_flake_reference_parse_flags in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixFlakeReferenceParseFlagsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixFlakeReferenceParseFlagsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixFlakeReferenceParseFlagsValue = unsafe.Sizeof([1]C.nix_flake_reference_parse_flags{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixFlakeReferenceParseFlags) PassRef() *C.nix_flake_reference_parse_flags {
	if x == nil {
		x = (*NixFlakeReferenceParseFlags)(allocNixFlakeReferenceParseFlagsMemory(1))
	}
	return (*C.nix_flake_reference_parse_flags)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixFlakeReference) Ref() *C.nix_flake_reference {
	if x == nil {
		return nil
	}
	return (*C.nix_flake_reference)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixFlakeReference) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixFlakeReferenceRef converts the C object reference into a raw struct reference without wrapping.
func NewNixFlakeReferenceRef(ref unsafe.Pointer) *NixFlakeReference {
	return (*NixFlakeReference)(ref)
}

// NewNixFlakeReference allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixFlakeReference() *NixFlakeReference {
	return (*NixFlakeReference)(allocNixFlakeReferenceMemory(1))
}

// allocNixFlakeReferenceMemory allocates memory for type C.nix_flake_reference in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixFlakeReferenceMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixFlakeReferenceValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixFlakeReferenceValue = unsafe.Sizeof([1]C.nix_flake_reference{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixFlakeReference) PassRef() *C.nix_flake_reference {
	if x == nil {
		x = (*NixFlakeReference)(allocNixFlakeReferenceMemory(1))
	}
	return (*C.nix_flake_reference)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixFlakeLockFlags) Ref() *C.nix_flake_lock_flags {
	if x == nil {
		return nil
	}
	return (*C.nix_flake_lock_flags)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixFlakeLockFlags) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixFlakeLockFlagsRef converts the C object reference into a raw struct reference without wrapping.
func NewNixFlakeLockFlagsRef(ref unsafe.Pointer) *NixFlakeLockFlags {
	return (*NixFlakeLockFlags)(ref)
}

// NewNixFlakeLockFlags allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixFlakeLockFlags() *NixFlakeLockFlags {
	return (*NixFlakeLockFlags)(allocNixFlakeLockFlagsMemory(1))
}

// allocNixFlakeLockFlagsMemory allocates memory for type C.nix_flake_lock_flags in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixFlakeLockFlagsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixFlakeLockFlagsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixFlakeLockFlagsValue = unsafe.Sizeof([1]C.nix_flake_lock_flags{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixFlakeLockFlags) PassRef() *C.nix_flake_lock_flags {
	if x == nil {
		x = (*NixFlakeLockFlags)(allocNixFlakeLockFlagsMemory(1))
	}
	return (*C.nix_flake_lock_flags)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixLockedFlake) Ref() *C.nix_locked_flake {
	if x == nil {
		return nil
	}
	return (*C.nix_locked_flake)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixLockedFlake) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixLockedFlakeRef converts the C object reference into a raw struct reference without wrapping.
func NewNixLockedFlakeRef(ref unsafe.Pointer) *NixLockedFlake {
	return (*NixLockedFlake)(ref)
}

// NewNixLockedFlake allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixLockedFlake() *NixLockedFlake {
	return (*NixLockedFlake)(allocNixLockedFlakeMemory(1))
}

// allocNixLockedFlakeMemory allocates memory for type C.nix_locked_flake in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixLockedFlakeMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixLockedFlakeValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixLockedFlakeValue = unsafe.Sizeof([1]C.nix_locked_flake{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixLockedFlake) PassRef() *C.nix_locked_flake {
	if x == nil {
		x = (*NixLockedFlake)(allocNixLockedFlakeMemory(1))
	}
	return (*C.nix_locked_flake)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *Store) Ref() *C.Store {
	if x == nil {
		return nil
	}
	return (*C.Store)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Store) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewStoreRef converts the C object reference into a raw struct reference without wrapping.
func NewStoreRef(ref unsafe.Pointer) *Store {
	return (*Store)(ref)
}

// NewStore allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewStore() *Store {
	return (*Store)(allocStoreMemory(1))
}

// allocStoreMemory allocates memory for type C.Store in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreValue = unsafe.Sizeof([1]C.Store{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Store) PassRef() *C.Store {
	if x == nil {
		x = (*Store)(allocStoreMemory(1))
	}
	return (*C.Store)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixDerivation) Ref() *C.nix_derivation {
	if x == nil {
		return nil
	}
	return (*C.nix_derivation)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixDerivation) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixDerivationRef converts the C object reference into a raw struct reference without wrapping.
func NewNixDerivationRef(ref unsafe.Pointer) *NixDerivation {
	return (*NixDerivation)(ref)
}

// NewNixDerivation allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixDerivation() *NixDerivation {
	return (*NixDerivation)(allocNixDerivationMemory(1))
}

// allocNixDerivationMemory allocates memory for type C.nix_derivation in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixDerivationMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixDerivationValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixDerivationValue = unsafe.Sizeof([1]C.nix_derivation{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixDerivation) PassRef() *C.nix_derivation {
	if x == nil {
		x = (*NixDerivation)(allocNixDerivationMemory(1))
	}
	return (*C.nix_derivation)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *StorePath) Ref() *C.StorePath {
	if x == nil {
		return nil
	}
	return (*C.StorePath)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *StorePath) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewStorePathRef converts the C object reference into a raw struct reference without wrapping.
func NewStorePathRef(ref unsafe.Pointer) *StorePath {
	return (*StorePath)(ref)
}

// NewStorePath allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewStorePath() *StorePath {
	return (*StorePath)(allocStorePathMemory(1))
}

// allocStorePathMemory allocates memory for type C.StorePath in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStorePathMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStorePathValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStorePathValue = unsafe.Sizeof([1]C.StorePath{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *StorePath) PassRef() *C.StorePath {
	if x == nil {
		x = (*StorePath)(allocStorePathMemory(1))
	}
	return (*C.StorePath)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixCContext) Ref() *C.nix_c_context {
	if x == nil {
		return nil
	}
	return (*C.nix_c_context)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixCContext) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixCContextRef converts the C object reference into a raw struct reference without wrapping.
func NewNixCContextRef(ref unsafe.Pointer) *NixCContext {
	return (*NixCContext)(ref)
}

// NewNixCContext allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixCContext() *NixCContext {
	return (*NixCContext)(allocNixCContextMemory(1))
}

// allocNixCContextMemory allocates memory for type C.nix_c_context in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixCContextMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixCContextValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixCContextValue = unsafe.Sizeof([1]C.nix_c_context{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixCContext) PassRef() *C.nix_c_context {
	if x == nil {
		x = (*NixCContext)(allocNixCContextMemory(1))
	}
	return (*C.nix_c_context)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *BindingsBuilder) Ref() *C.BindingsBuilder {
	if x == nil {
		return nil
	}
	return (*C.BindingsBuilder)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *BindingsBuilder) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewBindingsBuilderRef converts the C object reference into a raw struct reference without wrapping.
func NewBindingsBuilderRef(ref unsafe.Pointer) *BindingsBuilder {
	return (*BindingsBuilder)(ref)
}

// NewBindingsBuilder allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewBindingsBuilder() *BindingsBuilder {
	return (*BindingsBuilder)(allocBindingsBuilderMemory(1))
}

// allocBindingsBuilderMemory allocates memory for type C.BindingsBuilder in C.
// The caller is responsible for freeing the this memory via C.free.
func allocBindingsBuilderMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfBindingsBuilderValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfBindingsBuilderValue = unsafe.Sizeof([1]C.BindingsBuilder{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *BindingsBuilder) PassRef() *C.BindingsBuilder {
	if x == nil {
		x = (*BindingsBuilder)(allocBindingsBuilderMemory(1))
	}
	return (*C.BindingsBuilder)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *ListBuilder) Ref() *C.ListBuilder {
	if x == nil {
		return nil
	}
	return (*C.ListBuilder)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *ListBuilder) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewListBuilderRef converts the C object reference into a raw struct reference without wrapping.
func NewListBuilderRef(ref unsafe.Pointer) *ListBuilder {
	return (*ListBuilder)(ref)
}

// NewListBuilder allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewListBuilder() *ListBuilder {
	return (*ListBuilder)(allocListBuilderMemory(1))
}

// allocListBuilderMemory allocates memory for type C.ListBuilder in C.
// The caller is responsible for freeing the this memory via C.free.
func allocListBuilderMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfListBuilderValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfListBuilderValue = unsafe.Sizeof([1]C.ListBuilder{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *ListBuilder) PassRef() *C.ListBuilder {
	if x == nil {
		x = (*ListBuilder)(allocListBuilderMemory(1))
	}
	return (*C.ListBuilder)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *PrimOp) Ref() *C.PrimOp {
	if x == nil {
		return nil
	}
	return (*C.PrimOp)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *PrimOp) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewPrimOpRef converts the C object reference into a raw struct reference without wrapping.
func NewPrimOpRef(ref unsafe.Pointer) *PrimOp {
	return (*PrimOp)(ref)
}

// NewPrimOp allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewPrimOp() *PrimOp {
	return (*PrimOp)(allocPrimOpMemory(1))
}

// allocPrimOpMemory allocates memory for type C.PrimOp in C.
// The caller is responsible for freeing the this memory via C.free.
func allocPrimOpMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfPrimOpValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfPrimOpValue = unsafe.Sizeof([1]C.PrimOp{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *PrimOp) PassRef() *C.PrimOp {
	if x == nil {
		x = (*PrimOp)(allocPrimOpMemory(1))
	}
	return (*C.PrimOp)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *ExternalValue) Ref() *C.ExternalValue {
	if x == nil {
		return nil
	}
	return (*C.ExternalValue)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *ExternalValue) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewExternalValueRef converts the C object reference into a raw struct reference without wrapping.
func NewExternalValueRef(ref unsafe.Pointer) *ExternalValue {
	return (*ExternalValue)(ref)
}

// NewExternalValue allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewExternalValue() *ExternalValue {
	return (*ExternalValue)(allocExternalValueMemory(1))
}

// allocExternalValueMemory allocates memory for type C.ExternalValue in C.
// The caller is responsible for freeing the this memory via C.free.
func allocExternalValueMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfExternalValueValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfExternalValueValue = unsafe.Sizeof([1]C.ExternalValue{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *ExternalValue) PassRef() *C.ExternalValue {
	if x == nil {
		x = (*ExternalValue)(allocExternalValueMemory(1))
	}
	return (*C.ExternalValue)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *NixRealisedString) Ref() *C.nix_realised_string {
	if x == nil {
		return nil
	}
	return (*C.nix_realised_string)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *NixRealisedString) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewNixRealisedStringRef converts the C object reference into a raw struct reference without wrapping.
func NewNixRealisedStringRef(ref unsafe.Pointer) *NixRealisedString {
	return (*NixRealisedString)(ref)
}

// NewNixRealisedString allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewNixRealisedString() *NixRealisedString {
	return (*NixRealisedString)(allocNixRealisedStringMemory(1))
}

// allocNixRealisedStringMemory allocates memory for type C.nix_realised_string in C.
// The caller is responsible for freeing the this memory via C.free.
func allocNixRealisedStringMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfNixRealisedStringValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfNixRealisedStringValue = unsafe.Sizeof([1]C.nix_realised_string{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *NixRealisedString) PassRef() *C.nix_realised_string {
	if x == nil {
		x = (*NixRealisedString)(allocNixRealisedStringMemory(1))
	}
	return (*C.nix_realised_string)(unsafe.Pointer(x))
}

// allocStringItemMemory allocates memory for type C.go_nix_string_item in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStringItemMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStringItemValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStringItemValue = unsafe.Sizeof([1]C.go_nix_string_item{})

// copyPCharBytes copies the data from Go slice as *C.char.
func copyPCharBytes(slice *sliceHeader) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfCharValue) * slice.Len,
		Cap:  int(sizeOfCharValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.char)(mem0), allocs
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocCharMemory allocates memory for type C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfCharValue = unsafe.Sizeof([1]C.char{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StringItem) Ref() *C.go_nix_string_item {
	if x == nil {
		return nil
	}
	return x.ref72036a06
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StringItem) Free() {
	if x != nil && x.allocs72036a06 != nil {
		x.allocs72036a06.(*cgoAllocMap).Free()
		x.ref72036a06 = nil
	}
}

// NewStringItemRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStringItemRef(ref unsafe.Pointer) *StringItem {
	if ref == nil {
		return nil
	}
	obj := new(StringItem)
	obj.ref72036a06 = (*C.go_nix_string_item)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StringItem) PassRef() (*C.go_nix_string_item, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref72036a06 != nil {
		return x.ref72036a06, nil
	}
	mem72036a06 := allocStringItemMemory(1)
	ref72036a06 := (*C.go_nix_string_item)(mem72036a06)
	allocs72036a06 := new(cgoAllocMap)
	allocs72036a06.Add(mem72036a06)

	var cvalue_allocs *cgoAllocMap
	ref72036a06.value, cvalue_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Value)))
	allocs72036a06.Borrow(cvalue_allocs)

	var clen_allocs *cgoAllocMap
	ref72036a06.len, clen_allocs = (C.size_t)(x.Len), cgoAllocsUnknown
	allocs72036a06.Borrow(clen_allocs)

	x.ref72036a06 = ref72036a06
	x.allocs72036a06 = allocs72036a06
	return ref72036a06, allocs72036a06

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StringItem) PassValue() (C.go_nix_string_item, *cgoAllocMap) {
	if x.ref72036a06 != nil {
		return *x.ref72036a06, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StringItem) Deref() {
	if x.ref72036a06 == nil {
		return
	}
	hxfc4425b := (*sliceHeader)(unsafe.Pointer(&x.Value))
	hxfc4425b.Data = unsafe.Pointer(x.ref72036a06.value)
	hxfc4425b.Cap = 0x7fffffff
	// hxfc4425b.Len = ? x.Value x.ref72036a06.value

	x.Len = (uint64)(x.ref72036a06.len)
}

// allocStringArrayMemory allocates memory for type C.go_nix_string_array in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStringArrayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStringArrayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStringArrayValue = unsafe.Sizeof([1]C.go_nix_string_array{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// unpackSStringItem transforms a sliced Go data structure into plain C format.
func unpackSStringItem(x []StringItem) (unpacked *C.go_nix_string_item, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStringItemMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.go_nix_string_item)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.go_nix_string_item)(h.Data)
	return
}

// packSStringItem reads sliced Go data structure out from plain C format.
func packSStringItem(v []StringItem, ptr0 *C.go_nix_string_item) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStringItemValue]C.go_nix_string_item)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewStringItemRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StringArray) Ref() *C.go_nix_string_array {
	if x == nil {
		return nil
	}
	return x.refb20d6eae
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StringArray) Free() {
	if x != nil && x.allocsb20d6eae != nil {
		x.allocsb20d6eae.(*cgoAllocMap).Free()
		x.refb20d6eae = nil
	}
}

// NewStringArrayRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStringArrayRef(ref unsafe.Pointer) *StringArray {
	if ref == nil {
		return nil
	}
	obj := new(StringArray)
	obj.refb20d6eae = (*C.go_nix_string_array)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StringArray) PassRef() (*C.go_nix_string_array, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refb20d6eae != nil {
		return x.refb20d6eae, nil
	}
	memb20d6eae := allocStringArrayMemory(1)
	refb20d6eae := (*C.go_nix_string_array)(memb20d6eae)
	allocsb20d6eae := new(cgoAllocMap)
	allocsb20d6eae.Add(memb20d6eae)

	var citems_allocs *cgoAllocMap
	refb20d6eae.items, citems_allocs = unpackSStringItem(x.Items)
	allocsb20d6eae.Borrow(citems_allocs)

	var clen_allocs *cgoAllocMap
	refb20d6eae.len, clen_allocs = (C.size_t)(x.Len), cgoAllocsUnknown
	allocsb20d6eae.Borrow(clen_allocs)

	x.refb20d6eae = refb20d6eae
	x.allocsb20d6eae = allocsb20d6eae
	return refb20d6eae, allocsb20d6eae

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StringArray) PassValue() (C.go_nix_string_array, *cgoAllocMap) {
	if x.refb20d6eae != nil {
		return *x.refb20d6eae, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StringArray) Deref() {
	if x.refb20d6eae == nil {
		return
	}
	packSStringItem(x.Items, x.refb20d6eae.items)
	x.Len = (uint64)(x.refb20d6eae.len)
}

// allocValueItemMemory allocates memory for type C.go_nix_value_item in C.
// The caller is responsible for freeing the this memory via C.free.
func allocValueItemMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfValueItemValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfValueItemValue = unsafe.Sizeof([1]C.go_nix_value_item{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *ValueItem) Ref() *C.go_nix_value_item {
	if x == nil {
		return nil
	}
	return x.refa57cd5ac
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *ValueItem) Free() {
	if x != nil && x.allocsa57cd5ac != nil {
		x.allocsa57cd5ac.(*cgoAllocMap).Free()
		x.refa57cd5ac = nil
	}
}

// NewValueItemRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewValueItemRef(ref unsafe.Pointer) *ValueItem {
	if ref == nil {
		return nil
	}
	obj := new(ValueItem)
	obj.refa57cd5ac = (*C.go_nix_value_item)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *ValueItem) PassRef() (*C.go_nix_value_item, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.refa57cd5ac != nil {
		return x.refa57cd5ac, nil
	}
	mema57cd5ac := allocValueItemMemory(1)
	refa57cd5ac := (*C.go_nix_value_item)(mema57cd5ac)
	allocsa57cd5ac := new(cgoAllocMap)
	allocsa57cd5ac.Add(mema57cd5ac)

	var cvalue_allocs *cgoAllocMap
	refa57cd5ac.value, cvalue_allocs = *(**C.nix_value)(unsafe.Pointer(&x.Value)), cgoAllocsUnknown
	allocsa57cd5ac.Borrow(cvalue_allocs)

	x.refa57cd5ac = refa57cd5ac
	x.allocsa57cd5ac = allocsa57cd5ac
	return refa57cd5ac, allocsa57cd5ac

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x ValueItem) PassValue() (C.go_nix_value_item, *cgoAllocMap) {
	if x.refa57cd5ac != nil {
		return *x.refa57cd5ac, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *ValueItem) Deref() {
	if x.refa57cd5ac == nil {
		return
	}
	x.Value = (*NixValue)(unsafe.Pointer(x.refa57cd5ac.value))
}

// allocValueArrayMemory allocates memory for type C.go_nix_value_array in C.
// The caller is responsible for freeing the this memory via C.free.
func allocValueArrayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfValueArrayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfValueArrayValue = unsafe.Sizeof([1]C.go_nix_value_array{})

// unpackSValueItem transforms a sliced Go data structure into plain C format.
func unpackSValueItem(x []ValueItem) (unpacked *C.go_nix_value_item, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocValueItemMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.go_nix_value_item)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.go_nix_value_item)(h.Data)
	return
}

// packSValueItem reads sliced Go data structure out from plain C format.
func packSValueItem(v []ValueItem, ptr0 *C.go_nix_value_item) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfValueItemValue]C.go_nix_value_item)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewValueItemRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *ValueArray) Ref() *C.go_nix_value_array {
	if x == nil {
		return nil
	}
	return x.ref84d95be7
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *ValueArray) Free() {
	if x != nil && x.allocs84d95be7 != nil {
		x.allocs84d95be7.(*cgoAllocMap).Free()
		x.ref84d95be7 = nil
	}
}

// NewValueArrayRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewValueArrayRef(ref unsafe.Pointer) *ValueArray {
	if ref == nil {
		return nil
	}
	obj := new(ValueArray)
	obj.ref84d95be7 = (*C.go_nix_value_array)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *ValueArray) PassRef() (*C.go_nix_value_array, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref84d95be7 != nil {
		return x.ref84d95be7, nil
	}
	mem84d95be7 := allocValueArrayMemory(1)
	ref84d95be7 := (*C.go_nix_value_array)(mem84d95be7)
	allocs84d95be7 := new(cgoAllocMap)
	allocs84d95be7.Add(mem84d95be7)

	var citems_allocs *cgoAllocMap
	ref84d95be7.items, citems_allocs = unpackSValueItem(x.Items)
	allocs84d95be7.Borrow(citems_allocs)

	var clen_allocs *cgoAllocMap
	ref84d95be7.len, clen_allocs = (C.size_t)(x.Len), cgoAllocsUnknown
	allocs84d95be7.Borrow(clen_allocs)

	x.ref84d95be7 = ref84d95be7
	x.allocs84d95be7 = allocs84d95be7
	return ref84d95be7, allocs84d95be7

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x ValueArray) PassValue() (C.go_nix_value_array, *cgoAllocMap) {
	if x.ref84d95be7 != nil {
		return *x.ref84d95be7, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *ValueArray) Deref() {
	if x.ref84d95be7 == nil {
		return
	}
	packSValueItem(x.Items, x.ref84d95be7.items)
	x.Len = (uint64)(x.ref84d95be7.len)
}

// Ref returns a reference to C object as it is.
func (x *FlakeReferenceResult) Ref() *C.go_nix_flake_reference_result {
	if x == nil {
		return nil
	}
	return (*C.go_nix_flake_reference_result)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *FlakeReferenceResult) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewFlakeReferenceResultRef converts the C object reference into a raw struct reference without wrapping.
func NewFlakeReferenceResultRef(ref unsafe.Pointer) *FlakeReferenceResult {
	return (*FlakeReferenceResult)(ref)
}

// NewFlakeReferenceResult allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewFlakeReferenceResult() *FlakeReferenceResult {
	return (*FlakeReferenceResult)(allocFlakeReferenceResultMemory(1))
}

// allocFlakeReferenceResultMemory allocates memory for type C.go_nix_flake_reference_result in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFlakeReferenceResultMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFlakeReferenceResultValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFlakeReferenceResultValue = unsafe.Sizeof([1]C.go_nix_flake_reference_result{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *FlakeReferenceResult) PassRef() *C.go_nix_flake_reference_result {
	if x == nil {
		x = (*FlakeReferenceResult)(allocFlakeReferenceResultMemory(1))
	}
	return (*C.go_nix_flake_reference_result)(unsafe.Pointer(x))
}

// allocStoreParamMemory allocates memory for type C.go_nix_store_param in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreParamMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreParamValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreParamValue = unsafe.Sizeof([1]C.go_nix_store_param{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StoreParam) Ref() *C.go_nix_store_param {
	if x == nil {
		return nil
	}
	return x.ref2b71aeb
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StoreParam) Free() {
	if x != nil && x.allocs2b71aeb != nil {
		x.allocs2b71aeb.(*cgoAllocMap).Free()
		x.ref2b71aeb = nil
	}
}

// NewStoreParamRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStoreParamRef(ref unsafe.Pointer) *StoreParam {
	if ref == nil {
		return nil
	}
	obj := new(StoreParam)
	obj.ref2b71aeb = (*C.go_nix_store_param)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StoreParam) PassRef() (*C.go_nix_store_param, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref2b71aeb != nil {
		return x.ref2b71aeb, nil
	}
	mem2b71aeb := allocStoreParamMemory(1)
	ref2b71aeb := (*C.go_nix_store_param)(mem2b71aeb)
	allocs2b71aeb := new(cgoAllocMap)
	allocs2b71aeb.Add(mem2b71aeb)

	var ckey_allocs *cgoAllocMap
	ref2b71aeb.key, ckey_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Key)))
	allocs2b71aeb.Borrow(ckey_allocs)

	var ckey_len_allocs *cgoAllocMap
	ref2b71aeb.key_len, ckey_len_allocs = (C.size_t)(x.KeyLen), cgoAllocsUnknown
	allocs2b71aeb.Borrow(ckey_len_allocs)

	var cvalue_allocs *cgoAllocMap
	ref2b71aeb.value, cvalue_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Value)))
	allocs2b71aeb.Borrow(cvalue_allocs)

	var cvalue_len_allocs *cgoAllocMap
	ref2b71aeb.value_len, cvalue_len_allocs = (C.size_t)(x.ValueLen), cgoAllocsUnknown
	allocs2b71aeb.Borrow(cvalue_len_allocs)

	x.ref2b71aeb = ref2b71aeb
	x.allocs2b71aeb = allocs2b71aeb
	return ref2b71aeb, allocs2b71aeb

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StoreParam) PassValue() (C.go_nix_store_param, *cgoAllocMap) {
	if x.ref2b71aeb != nil {
		return *x.ref2b71aeb, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StoreParam) Deref() {
	if x.ref2b71aeb == nil {
		return
	}
	hxf95e7c8 := (*sliceHeader)(unsafe.Pointer(&x.Key))
	hxf95e7c8.Data = unsafe.Pointer(x.ref2b71aeb.key)
	hxf95e7c8.Cap = 0x7fffffff
	// hxf95e7c8.Len = ? x.Key x.ref2b71aeb.key

	x.KeyLen = (uint64)(x.ref2b71aeb.key_len)
	hxff2234b := (*sliceHeader)(unsafe.Pointer(&x.Value))
	hxff2234b.Data = unsafe.Pointer(x.ref2b71aeb.value)
	hxff2234b.Cap = 0x7fffffff
	// hxff2234b.Len = ? x.Value x.ref2b71aeb.value

	x.ValueLen = (uint64)(x.ref2b71aeb.value_len)
}

// allocStoreParamsMemory allocates memory for type C.go_nix_store_params in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreParamsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreParamsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreParamsValue = unsafe.Sizeof([1]C.go_nix_store_params{})

// unpackSStoreParam transforms a sliced Go data structure into plain C format.
func unpackSStoreParam(x []StoreParam) (unpacked *C.go_nix_store_param, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocStoreParamMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.go_nix_store_param)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.go_nix_store_param)(h.Data)
	return
}

// packSStoreParam reads sliced Go data structure out from plain C format.
func packSStoreParam(v []StoreParam, ptr0 *C.go_nix_store_param) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfStoreParamValue]C.go_nix_store_param)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewStoreParamRef(unsafe.Pointer(&ptr1))
	}
}

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StoreParams) Ref() *C.go_nix_store_params {
	if x == nil {
		return nil
	}
	return x.ref2cd443e1
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StoreParams) Free() {
	if x != nil && x.allocs2cd443e1 != nil {
		x.allocs2cd443e1.(*cgoAllocMap).Free()
		x.ref2cd443e1 = nil
	}
}

// NewStoreParamsRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStoreParamsRef(ref unsafe.Pointer) *StoreParams {
	if ref == nil {
		return nil
	}
	obj := new(StoreParams)
	obj.ref2cd443e1 = (*C.go_nix_store_params)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StoreParams) PassRef() (*C.go_nix_store_params, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref2cd443e1 != nil {
		return x.ref2cd443e1, nil
	}
	mem2cd443e1 := allocStoreParamsMemory(1)
	ref2cd443e1 := (*C.go_nix_store_params)(mem2cd443e1)
	allocs2cd443e1 := new(cgoAllocMap)
	allocs2cd443e1.Add(mem2cd443e1)

	var citems_allocs *cgoAllocMap
	ref2cd443e1.items, citems_allocs = unpackSStoreParam(x.Items)
	allocs2cd443e1.Borrow(citems_allocs)

	var clen_allocs *cgoAllocMap
	ref2cd443e1.len, clen_allocs = (C.size_t)(x.Len), cgoAllocsUnknown
	allocs2cd443e1.Borrow(clen_allocs)

	x.ref2cd443e1 = ref2cd443e1
	x.allocs2cd443e1 = allocs2cd443e1
	return ref2cd443e1, allocs2cd443e1

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StoreParams) PassValue() (C.go_nix_store_params, *cgoAllocMap) {
	if x.ref2cd443e1 != nil {
		return *x.ref2cd443e1, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StoreParams) Deref() {
	if x.ref2cd443e1 == nil {
		return
	}
	packSStoreParam(x.Items, x.ref2cd443e1.items)
	x.Len = (uint64)(x.ref2cd443e1.len)
}

// allocStorePathHashPartMemory allocates memory for type C.go_nix_store_path_hash_part in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStorePathHashPartMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStorePathHashPartValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStorePathHashPartValue = unsafe.Sizeof([1]C.go_nix_store_path_hash_part{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *StorePathHashPart) Ref() *C.go_nix_store_path_hash_part {
	if x == nil {
		return nil
	}
	return x.reff3a80ce6
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *StorePathHashPart) Free() {
	if x != nil && x.allocsf3a80ce6 != nil {
		x.allocsf3a80ce6.(*cgoAllocMap).Free()
		x.reff3a80ce6 = nil
	}
}

// NewStorePathHashPartRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewStorePathHashPartRef(ref unsafe.Pointer) *StorePathHashPart {
	if ref == nil {
		return nil
	}
	obj := new(StorePathHashPart)
	obj.reff3a80ce6 = (*C.go_nix_store_path_hash_part)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *StorePathHashPart) PassRef() (*C.go_nix_store_path_hash_part, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.reff3a80ce6 != nil {
		return x.reff3a80ce6, nil
	}
	memf3a80ce6 := allocStorePathHashPartMemory(1)
	reff3a80ce6 := (*C.go_nix_store_path_hash_part)(memf3a80ce6)
	allocsf3a80ce6 := new(cgoAllocMap)
	allocsf3a80ce6.Add(memf3a80ce6)

	var cbytes_allocs *cgoAllocMap
	reff3a80ce6.bytes, cbytes_allocs = *(*[20]C.uchar)(unsafe.Pointer(&x.Bytes)), cgoAllocsUnknown
	allocsf3a80ce6.Borrow(cbytes_allocs)

	x.reff3a80ce6 = reff3a80ce6
	x.allocsf3a80ce6 = allocsf3a80ce6
	return reff3a80ce6, allocsf3a80ce6

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x StorePathHashPart) PassValue() (C.go_nix_store_path_hash_part, *cgoAllocMap) {
	if x.reff3a80ce6 != nil {
		return *x.reff3a80ce6, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *StorePathHashPart) Deref() {
	if x.reff3a80ce6 == nil {
		return
	}
	x.Bytes = *(*[20]byte)(unsafe.Pointer(&x.reff3a80ce6.bytes))
}

// Ref returns a reference to C object as it is.
func (x *StoreRealiseResults) Ref() *C.go_nix_store_realise_results {
	if x == nil {
		return nil
	}
	return (*C.go_nix_store_realise_results)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *StoreRealiseResults) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewStoreRealiseResultsRef converts the C object reference into a raw struct reference without wrapping.
func NewStoreRealiseResultsRef(ref unsafe.Pointer) *StoreRealiseResults {
	return (*StoreRealiseResults)(ref)
}

// NewStoreRealiseResults allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewStoreRealiseResults() *StoreRealiseResults {
	return (*StoreRealiseResults)(allocStoreRealiseResultsMemory(1))
}

// allocStoreRealiseResultsMemory allocates memory for type C.go_nix_store_realise_results in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStoreRealiseResultsMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStoreRealiseResultsValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStoreRealiseResultsValue = unsafe.Sizeof([1]C.go_nix_store_realise_results{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *StoreRealiseResults) PassRef() *C.go_nix_store_realise_results {
	if x == nil {
		x = (*StoreRealiseResults)(allocStoreRealiseResultsMemory(1))
	}
	return (*C.go_nix_store_realise_results)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *StorePathArray) Ref() *C.go_nix_store_path_array {
	if x == nil {
		return nil
	}
	return (*C.go_nix_store_path_array)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *StorePathArray) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewStorePathArrayRef converts the C object reference into a raw struct reference without wrapping.
func NewStorePathArrayRef(ref unsafe.Pointer) *StorePathArray {
	return (*StorePathArray)(ref)
}

// NewStorePathArray allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewStorePathArray() *StorePathArray {
	return (*StorePathArray)(allocStorePathArrayMemory(1))
}

// allocStorePathArrayMemory allocates memory for type C.go_nix_store_path_array in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStorePathArrayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStorePathArrayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfStorePathArrayValue = unsafe.Sizeof([1]C.go_nix_store_path_array{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *StorePathArray) PassRef() *C.go_nix_store_path_array {
	if x == nil {
		x = (*StorePathArray)(allocStorePathArrayMemory(1))
	}
	return (*C.go_nix_store_path_array)(unsafe.Pointer(x))
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}
