// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c
#include "nix_go_util.h"
#include "nix_go_store.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// NixErr as declared in include/nix_api_util.h:121
type NixErr int32

// NixErr enumeration from include/nix_api_util.h:121
const (
	NixOk             NixErr = iota
	NixErrUnknown     NixErr = -1
	NixErrOverflow    NixErr = -2
	NixErrKey         NixErr = -3
	NixErrNixError    NixErr = -4
	NixErrRecoverable NixErr = -5
)

// NixVerbosity as declared in include/nix_api_util.h:139
type NixVerbosity int32

// NixVerbosity enumeration from include/nix_api_util.h:139
const (
	NixLvlError     NixVerbosity = iota
	NixLvlWarn      NixVerbosity = 1
	NixLvlNotice    NixVerbosity = 2
	NixLvlInfo      NixVerbosity = 3
	NixLvlTalkative NixVerbosity = 4
	NixLvlChatty    NixVerbosity = 5
	NixLvlDebug     NixVerbosity = 6
	NixLvlVomit     NixVerbosity = 7
)

const ()

const ()
