// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c nix-fetchers-c nix-expr-c nix-flake-c
#include "nix_go_util.h"
#include "nix_go_store.h"
#include "nix_go_fetchers.h"
#include "nix_go_expr.h"
#include "nix_go_flake.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// NixErr as declared in include/nix_api_util.h:121
type NixErr int32

// NixErr enumeration from include/nix_api_util.h:121
const (
	NixOk             NixErr = iota
	NixErrUnknown     NixErr = -1
	NixErrOverflow    NixErr = -2
	NixErrKey         NixErr = -3
	NixErrNixError    NixErr = -4
	NixErrRecoverable NixErr = -5
)

// NixVerbosity as declared in include/nix_api_util.h:139
type NixVerbosity int32

// NixVerbosity enumeration from include/nix_api_util.h:139
const (
	NixLvlError     NixVerbosity = iota
	NixLvlWarn      NixVerbosity = 1
	NixLvlNotice    NixVerbosity = 2
	NixLvlInfo      NixVerbosity = 3
	NixLvlTalkative NixVerbosity = 4
	NixLvlChatty    NixVerbosity = 5
	NixLvlDebug     NixVerbosity = 6
	NixLvlVomit     NixVerbosity = 7
)

// ValueType as declared in nix-go-bindings/nix_go_expr.h:39
type ValueType int32

// ValueType enumeration from nix-go-bindings/nix_go_expr.h:39
const (
	NixTypeThunk    ValueType = iota
	NixTypeInt      ValueType = 1
	NixTypeFloat    ValueType = 2
	NixTypeBool     ValueType = 3
	NixTypeString   ValueType = 4
	NixTypePath     ValueType = 5
	NixTypeNull     ValueType = 6
	NixTypeAttrs    ValueType = 7
	NixTypeList     ValueType = 8
	NixTypeFunction ValueType = 9
	NixTypeExternal ValueType = 10
	NixTypeFailed   ValueType = 11
)

const ()

const ()
