// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c
#include "nix_go_store.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// NixErr as declared in include/nix_api_util.h:121
type NixErr int32

// NixErr enumeration from include/nix_api_util.h:121
const ()

const ()

const ()
