// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c
#include "nix_go_util.h"
#include "nix_go_store.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// LibstoreInit function as declared in nix-go-bindings/nix_go_store.h:42
func LibstoreInit(ctx *NixCContext) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.go_nix_libstore_init(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// LibstoreInitNoLoadConfig function as declared in nix-go-bindings/nix_go_store.h:43
func LibstoreInitNoLoadConfig(ctx *NixCContext) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.go_nix_libstore_init_no_load_config(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// StoreOpen function as declared in nix-go-bindings/nix_go_store.h:45
func StoreOpen(ctx *NixCContext, uri string, params StoreParams) *Store {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	curi, curiAllocMap := unpackPCharString(uri)
	cparams, cparamsAllocMap := params.PassValue()
	__ret := C.go_nix_store_open(cctx, curi, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(curiAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**Store)(unsafe.Pointer(&__ret))
	return __v
}

// StoreFree function as declared in nix-go-bindings/nix_go_store.h:51
func StoreFree(store *Store) {
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	C.go_nix_store_free(cstore)
	runtime.KeepAlive(cstoreAllocMap)
}

// StoreGetUri function as declared in nix-go-bindings/nix_go_store.h:53
func StoreGetUri(ctx *NixCContext, store *Store) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	__ret := C.go_nix_store_get_uri(cctx, cstore)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// StoreGetStoredir function as declared in nix-go-bindings/nix_go_store.h:54
func StoreGetStoredir(ctx *NixCContext, store *Store) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	__ret := C.go_nix_store_get_storedir(cctx, cstore)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// StoreGetVersion function as declared in nix-go-bindings/nix_go_store.h:55
func StoreGetVersion(ctx *NixCContext, store *Store) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	__ret := C.go_nix_store_get_version(cctx, cstore)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// StoreRealPath function as declared in nix-go-bindings/nix_go_store.h:56
func StoreRealPath(ctx *NixCContext, store *Store, path *StorePath) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	__ret := C.go_nix_store_real_path(cctx, cstore, cpath)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// StoreParsePath function as declared in nix-go-bindings/nix_go_store.h:58
func StoreParsePath(ctx *NixCContext, store *Store, path string) *StorePath {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cpath, cpathAllocMap := unpackPCharString(path)
	__ret := C.go_nix_store_parse_path(cctx, cstore, cpath)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**StorePath)(unsafe.Pointer(&__ret))
	return __v
}

// StorePathClone function as declared in nix-go-bindings/nix_go_store.h:60
func StorePathClone(path *StorePath) *StorePath {
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	__ret := C.go_nix_store_path_clone(cpath)
	runtime.KeepAlive(cpathAllocMap)
	__v := *(**StorePath)(unsafe.Pointer(&__ret))
	return __v
}

// StorePathFree function as declared in nix-go-bindings/nix_go_store.h:61
func StorePathFree(path *StorePath) {
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	C.go_nix_store_path_free(cpath)
	runtime.KeepAlive(cpathAllocMap)
}

// StorePathName function as declared in nix-go-bindings/nix_go_store.h:62
func StorePathName(path *StorePath) *byte {
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	__ret := C.go_nix_store_path_name(cpath)
	runtime.KeepAlive(cpathAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// StorePathHash function as declared in nix-go-bindings/nix_go_store.h:63
func StorePathHash(ctx *NixCContext, path *StorePath, hash *StorePathHashPart) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	chash, chashAllocMap := hash.PassRef()
	__ret := C.go_nix_store_path_hash(cctx, cpath, chash)
	runtime.KeepAlive(chashAllocMap)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// StoreCreateFromParts function as declared in nix-go-bindings/nix_go_store.h:68
func StoreCreateFromParts(ctx *NixCContext, hash *StorePathHashPart, name string, nameLen uint64) *StorePath {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	chash, chashAllocMap := hash.PassRef()
	cname, cnameAllocMap := unpackPCharString(name)
	cnameLen, cnameLenAllocMap := (C.size_t)(nameLen), cgoAllocsUnknown
	__ret := C.go_nix_store_create_from_parts(cctx, chash, cname, cnameLen)
	runtime.KeepAlive(cnameLenAllocMap)
	runtime.KeepAlive(cnameAllocMap)
	runtime.KeepAlive(chashAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**StorePath)(unsafe.Pointer(&__ret))
	return __v
}

// StoreIsValidPath function as declared in nix-go-bindings/nix_go_store.h:75
func StoreIsValidPath(ctx *NixCContext, store *Store, path *StorePath) bool {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	__ret := C.go_nix_store_is_valid_path(cctx, cstore, cpath)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (bool)(__ret)
	return __v
}

// StoreRealise function as declared in nix-go-bindings/nix_go_store.h:81
func StoreRealise(ctx *NixCContext, store *Store, path *StorePath, userdata unsafe.Pointer, callback StoreRealiseCallback) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	cuserdata, cuserdataAllocMap := userdata, cgoAllocsUnknown
	ccallback, ccallbackAllocMap := callback.PassValue()
	__ret := C.go_nix_store_realise(cctx, cstore, cpath, cuserdata, ccallback)
	runtime.KeepAlive(ccallbackAllocMap)
	runtime.KeepAlive(cuserdataAllocMap)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// DerivationFromJson function as declared in nix-go-bindings/nix_go_store.h:89
func DerivationFromJson(ctx *NixCContext, store *Store, json string) *NixDerivation {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cjson, cjsonAllocMap := unpackPCharString(json)
	__ret := C.go_nix_derivation_from_json(cctx, cstore, cjson)
	runtime.KeepAlive(cjsonAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**NixDerivation)(unsafe.Pointer(&__ret))
	return __v
}

// AddDerivation function as declared in nix-go-bindings/nix_go_store.h:95
func AddDerivation(ctx *NixCContext, store *Store, derivation *NixDerivation) *StorePath {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cderivation, cderivationAllocMap := (*C.nix_derivation)(unsafe.Pointer(derivation)), cgoAllocsUnknown
	__ret := C.go_nix_add_derivation(cctx, cstore, cderivation)
	runtime.KeepAlive(cderivationAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**StorePath)(unsafe.Pointer(&__ret))
	return __v
}

// StoreCopyClosure function as declared in nix-go-bindings/nix_go_store.h:101
func StoreCopyClosure(ctx *NixCContext, srcStore *Store, dstStore *Store, path *StorePath) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	csrcStore, csrcStoreAllocMap := (*C.Store)(unsafe.Pointer(srcStore)), cgoAllocsUnknown
	cdstStore, cdstStoreAllocMap := (*C.Store)(unsafe.Pointer(dstStore)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	__ret := C.go_nix_store_copy_closure(cctx, csrcStore, cdstStore, cpath)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cdstStoreAllocMap)
	runtime.KeepAlive(csrcStoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// StoreGetFsClosure function as declared in nix-go-bindings/nix_go_store.h:108
func StoreGetFsClosure(ctx *NixCContext, store *Store, storePath *StorePath, flipDirection bool, includeOutputs bool, includeDerivers bool, userdata unsafe.Pointer, callback StorePathCallback) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cstorePath, cstorePathAllocMap := (*C.StorePath)(unsafe.Pointer(storePath)), cgoAllocsUnknown
	cflipDirection, cflipDirectionAllocMap := (C._Bool)(flipDirection), cgoAllocsUnknown
	cincludeOutputs, cincludeOutputsAllocMap := (C._Bool)(includeOutputs), cgoAllocsUnknown
	cincludeDerivers, cincludeDeriversAllocMap := (C._Bool)(includeDerivers), cgoAllocsUnknown
	cuserdata, cuserdataAllocMap := userdata, cgoAllocsUnknown
	ccallback, ccallbackAllocMap := callback.PassValue()
	__ret := C.go_nix_store_get_fs_closure(cctx, cstore, cstorePath, cflipDirection, cincludeOutputs, cincludeDerivers, cuserdata, ccallback)
	runtime.KeepAlive(ccallbackAllocMap)
	runtime.KeepAlive(cuserdataAllocMap)
	runtime.KeepAlive(cincludeDeriversAllocMap)
	runtime.KeepAlive(cincludeOutputsAllocMap)
	runtime.KeepAlive(cflipDirectionAllocMap)
	runtime.KeepAlive(cstorePathAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// StoreDrvFromStorePath function as declared in nix-go-bindings/nix_go_store.h:119
func StoreDrvFromStorePath(ctx *NixCContext, store *Store, path *StorePath) *NixDerivation {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	__ret := C.go_nix_store_drv_from_store_path(cctx, cstore, cpath)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**NixDerivation)(unsafe.Pointer(&__ret))
	return __v
}

// StoreQueryPathFromHashPart function as declared in nix-go-bindings/nix_go_store.h:125
func StoreQueryPathFromHashPart(ctx *NixCContext, store *Store, hash string) *StorePath {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cstore, cstoreAllocMap := (*C.Store)(unsafe.Pointer(store)), cgoAllocsUnknown
	chash, chashAllocMap := unpackPCharString(hash)
	__ret := C.go_nix_store_query_path_from_hash_part(cctx, cstore, chash)
	runtime.KeepAlive(chashAllocMap)
	runtime.KeepAlive(cstoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**StorePath)(unsafe.Pointer(&__ret))
	return __v
}

// StoreCopyPath function as declared in nix-go-bindings/nix_go_store.h:131
func StoreCopyPath(ctx *NixCContext, srcStore *Store, dstStore *Store, path *StorePath, repair bool, checkSigs bool) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	csrcStore, csrcStoreAllocMap := (*C.Store)(unsafe.Pointer(srcStore)), cgoAllocsUnknown
	cdstStore, cdstStoreAllocMap := (*C.Store)(unsafe.Pointer(dstStore)), cgoAllocsUnknown
	cpath, cpathAllocMap := (*C.StorePath)(unsafe.Pointer(path)), cgoAllocsUnknown
	crepair, crepairAllocMap := (C._Bool)(repair), cgoAllocsUnknown
	ccheckSigs, ccheckSigsAllocMap := (C._Bool)(checkSigs), cgoAllocsUnknown
	__ret := C.go_nix_store_copy_path(cctx, csrcStore, cdstStore, cpath, crepair, ccheckSigs)
	runtime.KeepAlive(ccheckSigsAllocMap)
	runtime.KeepAlive(crepairAllocMap)
	runtime.KeepAlive(cpathAllocMap)
	runtime.KeepAlive(cdstStoreAllocMap)
	runtime.KeepAlive(csrcStoreAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// CContextCreate function as declared in nix-go-bindings/nix_go_util.h:10
func CContextCreate() *NixCContext {
	__ret := C.go_nix_c_context_create()
	__v := *(**NixCContext)(unsafe.Pointer(&__ret))
	return __v
}

// CContextFree function as declared in nix-go-bindings/nix_go_util.h:11
func CContextFree(ctx *NixCContext) {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	C.go_nix_c_context_free(cctx)
	runtime.KeepAlive(cctxAllocMap)
}

// LibutilInit function as declared in nix-go-bindings/nix_go_util.h:13
func LibutilInit(ctx *NixCContext) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.go_nix_libutil_init(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// SettingGet function as declared in nix-go-bindings/nix_go_util.h:15
func SettingGet(ctx *NixCContext, key string) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ckey, ckeyAllocMap := unpackPCharString(key)
	__ret := C.go_nix_setting_get(cctx, ckey)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// SettingSet function as declared in nix-go-bindings/nix_go_util.h:16
func SettingSet(ctx *NixCContext, key string, value string) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ckey, ckeyAllocMap := unpackPCharString(key)
	cvalue, cvalueAllocMap := unpackPCharString(value)
	__ret := C.go_nix_setting_set(cctx, ckey, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// VersionGet function as declared in nix-go-bindings/nix_go_util.h:18
func VersionGet() *byte {
	__ret := C.go_nix_version_get()
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// ErrMsg function as declared in nix-go-bindings/nix_go_util.h:20
func ErrMsg(ctx *NixCContext, readCtx *NixCContext) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	creadCtx, creadCtxAllocMap := (*C.nix_c_context)(unsafe.Pointer(readCtx)), cgoAllocsUnknown
	__ret := C.go_nix_err_msg(cctx, creadCtx)
	runtime.KeepAlive(creadCtxAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// ErrInfoMsg function as declared in nix-go-bindings/nix_go_util.h:21
func ErrInfoMsg(ctx *NixCContext, readCtx *NixCContext) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	creadCtx, creadCtxAllocMap := (*C.nix_c_context)(unsafe.Pointer(readCtx)), cgoAllocsUnknown
	__ret := C.go_nix_err_info_msg(cctx, creadCtx)
	runtime.KeepAlive(creadCtxAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// ErrName function as declared in nix-go-bindings/nix_go_util.h:22
func ErrName(ctx *NixCContext, readCtx *NixCContext) *byte {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	creadCtx, creadCtxAllocMap := (*C.nix_c_context)(unsafe.Pointer(readCtx)), cgoAllocsUnknown
	__ret := C.go_nix_err_name(cctx, creadCtx)
	runtime.KeepAlive(creadCtxAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// ErrCode function as declared in nix-go-bindings/nix_go_util.h:23
func ErrCode(ctx *NixCContext) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.go_nix_err_code(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// SetErrMsg function as declared in nix-go-bindings/nix_go_util.h:24
func SetErrMsg(ctx *NixCContext, err NixErr, msg string) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cerr, cerrAllocMap := (C.nix_err)(err), cgoAllocsUnknown
	cmsg, cmsgAllocMap := unpackPCharString(msg)
	__ret := C.go_nix_set_err_msg(cctx, cerr, cmsg)
	runtime.KeepAlive(cmsgAllocMap)
	runtime.KeepAlive(cerrAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// ClearErr function as declared in nix-go-bindings/nix_go_util.h:25
func ClearErr(ctx *NixCContext) {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	C.go_nix_clear_err(cctx)
	runtime.KeepAlive(cctxAllocMap)
}

// SetVerbosity function as declared in nix-go-bindings/nix_go_util.h:27
func SetVerbosity(ctx *NixCContext, level NixVerbosity) NixErr {
	cctx, cctxAllocMap := (*C.nix_c_context)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.nix_verbosity)(level), cgoAllocsUnknown
	__ret := C.go_nix_set_verbosity(cctx, clevel)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (NixErr)(__ret)
	return __v
}

// StringFree function as declared in nix-go-bindings/nix_go_util.h:29
func StringFree(s *byte) {
	cs, csAllocMap := (*C.char)(unsafe.Pointer(s)), cgoAllocsUnknown
	C.go_nix_string_free(cs)
	runtime.KeepAlive(csAllocMap)
}
