// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c nix-fetchers-c nix-expr-c nix-flake-c
#include "nix_go_util.h"
#include "nix_go_store.h"
#include "nix_go_fetchers.h"
#include "nix_go_expr.h"
#include "nix_go_flake.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Store as declared in include/nix_api_store.h:25
type Store C.Store

// NixDerivation as declared in nix_api_store/derivation.h:21
type NixDerivation C.nix_derivation

// StorePath as declared in nix_api_store/store_path.h:24
type StorePath C.StorePath

// NixFetchersSettings as declared in include/nix_api_fetchers.h:22
type NixFetchersSettings C.nix_fetchers_settings

// NixFlakeSettings as declared in include/nix_api_flake.h:27
type NixFlakeSettings C.nix_flake_settings

// NixFlakeReferenceParseFlags as declared in include/nix_api_flake.h:34
type NixFlakeReferenceParseFlags C.nix_flake_reference_parse_flags

// NixFlakeReference as declared in include/nix_api_flake.h:44
type NixFlakeReference C.nix_flake_reference

// NixFlakeLockFlags as declared in include/nix_api_flake.h:52
type NixFlakeLockFlags C.nix_flake_lock_flags

// NixLockedFlake as declared in include/nix_api_flake.h:60
type NixLockedFlake C.nix_locked_flake

// NixCContext as declared in include/nix_api_util.h:160
type NixCContext C.nix_c_context

// NixEvalStateBuilder as declared in include/nix_api_expr.h:39
type NixEvalStateBuilder C.nix_eval_state_builder

// EvalState as declared in include/nix_api_expr.h:49
type EvalState C.EvalState

// NixValue as declared in include/nix_api_expr.h:69
type NixValue C.nix_value

// BindingsBuilder as declared in nix-go-bindings/nix_go_expr.h:17
type BindingsBuilder C.BindingsBuilder

// ListBuilder as declared in nix-go-bindings/nix_go_expr.h:18
type ListBuilder C.ListBuilder

// PrimOp as declared in nix-go-bindings/nix_go_expr.h:19
type PrimOp C.PrimOp

// ExternalValue as declared in nix-go-bindings/nix_go_expr.h:20
type ExternalValue C.ExternalValue

// NixRealisedString as declared in nix-go-bindings/nix_go_expr.h:21
type NixRealisedString C.nix_realised_string

// NixStringReturn as declared in nix-go-bindings/nix_go_expr.h:22
type NixStringReturn C.nix_string_return

// NixPrinter as declared in nix-go-bindings/nix_go_expr.h:23
type NixPrinter C.nix_printer

// NixStringContext as declared in nix-go-bindings/nix_go_expr.h:24
type NixStringContext C.nix_string_context

// StringItem as declared in nix-go-bindings/nix_go_expr.h:43
type StringItem struct {
	Value          []byte
	ref72036a06    *C.go_nix_string_item
	allocs72036a06 interface{}
}

// StringArray as declared in nix-go-bindings/nix_go_expr.h:48
type StringArray struct {
	Items          []StringItem
	Len            uint64
	refb20d6eae    *C.go_nix_string_array
	allocsb20d6eae interface{}
}

// ValueItem as declared in nix-go-bindings/nix_go_expr.h:52
type ValueItem struct {
	Value          *NixValue
	refa57cd5ac    *C.go_nix_value_item
	allocsa57cd5ac interface{}
}

// ValueArray as declared in nix-go-bindings/nix_go_expr.h:57
type ValueArray struct {
	Items          []ValueItem
	Len            uint64
	ref84d95be7    *C.go_nix_value_array
	allocs84d95be7 interface{}
}

// PrimopFun type as declared in nix-go-bindings/nix_go_expr.h:59
type PrimopFun func(userData unsafe.Pointer, context *NixCContext, state *EvalState, args **NixValue, ret *NixValue)

// Finalizer type as declared in nix-go-bindings/nix_go_expr.h:67
type Finalizer func(obj unsafe.Pointer, cd unsafe.Pointer)

// ExternalPrintFun type as declared in nix-go-bindings/nix_go_expr.h:69
type ExternalPrintFun func(self unsafe.Pointer, printer *NixPrinter)

// ExternalStringFun type as declared in nix-go-bindings/nix_go_expr.h:70
type ExternalStringFun func(self unsafe.Pointer, res *NixStringReturn)

// ExternalCoerceFun type as declared in nix-go-bindings/nix_go_expr.h:71
type ExternalCoerceFun func(self unsafe.Pointer, ctx *NixStringContext, coerceMore int32, copyToStore int32, res *NixStringReturn)

// ExternalEqualFun type as declared in nix-go-bindings/nix_go_expr.h:78
type ExternalEqualFun func(self unsafe.Pointer, other unsafe.Pointer) int32

// ExternalJsonFun type as declared in nix-go-bindings/nix_go_expr.h:79
type ExternalJsonFun func(self unsafe.Pointer, state *EvalState, strict bool, ctx *NixStringContext, copyToStore bool, res *NixStringReturn)

// ExternalXmlFun type as declared in nix-go-bindings/nix_go_expr.h:87
type ExternalXmlFun func(self unsafe.Pointer, state *EvalState, strict int32, location int32, doc unsafe.Pointer, ctx *NixStringContext, drvsSeen unsafe.Pointer, pos int32)

// ExternalValueDesc as declared in nix-go-bindings/nix_go_expr.h:106
type ExternalValueDesc struct {
	Print            ExternalPrintFun
	ShowType         ExternalStringFun
	TypeOf           ExternalStringFun
	CoerceToString   ExternalCoerceFun
	Equal            ExternalEqualFun
	PrintValueAsJson ExternalJsonFun
	PrintValueAsXml  ExternalXmlFun
	refaf0e485c      *C.go_nix_external_value_desc
	allocsaf0e485c   interface{}
}

// FlakeReferenceResult as declared in nix-go-bindings/nix_go_flake.h:19
type FlakeReferenceResult C.go_nix_flake_reference_result

// StoreParam as declared in nix-go-bindings/nix_go_store.h:19
type StoreParam struct {
	Key           []byte
	Value         []byte
	ref2b71aeb    *C.go_nix_store_param
	allocs2b71aeb interface{}
}

// StoreParams as declared in nix-go-bindings/nix_go_store.h:24
type StoreParams struct {
	Items          []StoreParam
	Len            uint64
	ref2cd443e1    *C.go_nix_store_params
	allocs2cd443e1 interface{}
}

// StorePathHashPart as declared in nix-go-bindings/nix_go_store.h:28
type StorePathHashPart struct {
	Bytes          [20]byte
	reff3a80ce6    *C.go_nix_store_path_hash_part
	allocsf3a80ce6 interface{}
}

// StoreRealiseCallback type as declared in nix-go-bindings/nix_go_store.h:30
type StoreRealiseCallback func(userdata unsafe.Pointer, outname string, out *StorePath)

// StorePathCallback type as declared in nix-go-bindings/nix_go_store.h:36
type StorePathCallback func(context *NixCContext, userdata unsafe.Pointer, storePath *StorePath)
