// LGPL-2.1-or-later

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nix

/*
#cgo pkg-config: nix-util-c nix-store-c
#include "nix_go_util.h"
#include "nix_go_store.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Store as declared in include/nix_api_store.h:25
type Store C.Store

// NixDerivation as declared in nix_api_store/derivation.h:21
type NixDerivation C.nix_derivation

// StorePath as declared in nix_api_store/store_path.h:24
type StorePath C.StorePath

// NixCContext as declared in include/nix_api_util.h:160
type NixCContext C.nix_c_context

// StoreParam as declared in nix-go-bindings/nix_go_store.h:19
type StoreParam struct {
	Key           []byte
	Value         []byte
	ref2b71aeb    *C.go_nix_store_param
	allocs2b71aeb interface{}
}

// StoreParams as declared in nix-go-bindings/nix_go_store.h:24
type StoreParams struct {
	Items          []StoreParam
	Len            uint64
	ref2cd443e1    *C.go_nix_store_params
	allocs2cd443e1 interface{}
}

// StoreRealiseCallback type as declared in nix-go-bindings/nix_go_store.h:26
type StoreRealiseCallback func(userdata unsafe.Pointer, outname string, out *StorePath)

// StorePathCallback type as declared in nix-go-bindings/nix_go_store.h:32
type StorePathCallback func(context *NixCContext, userdata unsafe.Pointer, storePath *StorePath)
